databaseChangeLog:
  - include:
      file: deploy/database/migrations/migration-[2024-01-08___23-53-59].sql
  - include:
      file: deploy/database/migrations/migration-[2024-01-09___00-01-48].sql
  - include:
      file: deploy/database/migrations/migration-[2024-01-09___00-25-55].sql

