-- liquibase formatted sql

-- changeset teamo:1704743639276-1
CREATE TABLE public.comment (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content VARCHAR(510), task_id BIGINT NOT NULL, user_id BIGINT NOT NULL, CONSTRAINT "commentPK" PRIMARY KEY (id));

-- changeset teamo:1704743639276-2
CREATE TABLE public.roles (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(40) NOT NULL, CONSTRAINT "rolesPK" PRIMARY KEY (id));

-- changeset teamo:1704743639276-3
CREATE TABLE public.tasks (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content VARCHAR(255), priority SMALLINT NOT NULL, status VARCHAR(40) NOT NULL, creator_id BIGINT NOT NULL, executor_id BIGINT, CONSTRAINT "tasksPK" PRIMARY KEY (id));

-- changeset teamo:1704743639276-4
CREATE TABLE public.users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255), password VARCHAR(255), username VARCHAR(255), CONSTRAINT "usersPK" PRIMARY KEY (id));

-- changeset teamo:1704743639276-5
CREATE TABLE public.users_roles (user_id BIGINT NOT NULL, role_id BIGINT NOT NULL);

-- changeset teamo:1704743639276-6
ALTER TABLE public.users ADD CONSTRAINT "UK6dotkott2kjsp8vw4d0m25fb7" UNIQUE (email);

-- changeset teamo:1704743639276-7
ALTER TABLE public.users ADD CONSTRAINT "UKr43af9ap4edm43mmtq01oddj6" UNIQUE (username);

-- changeset teamo:1704743639276-8
ALTER TABLE public.users_roles ADD CONSTRAINT "FK2o0jvgh89lemvvo17cbqvdxaa" FOREIGN KEY (user_id) REFERENCES public.users (id);

-- changeset teamo:1704743639276-9
ALTER TABLE public.tasks ADD CONSTRAINT "FKbrg922bkqn5m7212jsqjg6ioe" FOREIGN KEY (executor_id) REFERENCES public.users (id);

-- changeset teamo:1704743639276-10
ALTER TABLE public.comment ADD CONSTRAINT "FKfwc7uv5cfkqi3dnb2t20rnurc" FOREIGN KEY (task_id) REFERENCES public.tasks (id);

-- changeset teamo:1704743639276-11
ALTER TABLE public.users_roles ADD CONSTRAINT "FKj6m8fwv7oqv74fcehir1a9ffy" FOREIGN KEY (role_id) REFERENCES public.roles (id);

-- changeset teamo:1704743639276-12
ALTER TABLE public.comment ADD CONSTRAINT "FKqm52p1v3o13hy268he0wcngr5" FOREIGN KEY (user_id) REFERENCES public.users (id);

-- changeset teamo:1704743639276-13
ALTER TABLE public.tasks ADD CONSTRAINT "FKt1ph5sat39g9lpa4g5kl46tbv" FOREIGN KEY (creator_id) REFERENCES public.users (id);

