version: '3.3'
services:
  task_management_system:
    profiles: ["default"]
    image: 'task-management-system-image'
    container_name: task-management-system-container
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE}
    command: -Dspring.profiles.active=${PROFILE}
    depends_on:
      - task_management_system_db
    ports:
      - ${API_EXT_PORT}:${API_INT_PORT}
  task_management_system_db:
    profiles: ["default", "dev"]
    image: postgres
    restart: always
    container_name: task-management-system-db${CONTAINER_POSTFIX}
    environment:
      PGDATA: /var/lib/postgresql/data/task_management_system_db/
      POSTGRES_DB: task_management_system
      POSTGRES_USER: artem
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/tables.sql:/docker-entrypoint-initdb.d/tables.sql
      - /var/lib/deploy/volumes/task_management_system_db${CONTAINER_POSTFIX}/:/var/lib/postgresql/data/task_management_system_db${CONTAINER_POSTFIX}
    ports:
      - ${DB_EXT_PORT}:${DB_INT_PORT}
