version: '3.3'
services:
  task_management_sys_db:
    image: postgres
    restart: always
    container_name: task-management-sys-db
    environment:
      PGDATA: /var/lib/postgresql/data/task_management_sys/
      POSTGRES_DB: task_management_sys
      POSTGRES_USER: artem
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /var/lib/deploy/volumes/task_management_sys/:/var/lib/postgresql/data/task_management_sys
    ports:
      - 9876:5432