ARG ELK_VERSION
ARG ELK_IMAGE_PATH

# https://www.docker.elastic.co/
FROM ${ELK_IMAGE_PATH}logstash:${ELK_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
